//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAprendiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contratacao()
        {
            this.Frequencia = new HashSet<Frequencia>();
        }
    
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdMatricula { get; set; }
        public System.DateTime DataContratoInicio { get; set; }
        public Nullable<System.DateTime> DataMatriculaFim { get; set; }
        public System.DateTime DataInclusao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Matricula Matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Frequencia> Frequencia { get; set; }
    }
}
