//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAprendiz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntidade : DbContext
    {
        public DataEntidade()
            : base("name=DataEntidade")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atividade> Atividade { get; set; }
        public virtual DbSet<Contratacao> Contratacao { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<Frequencia> Frequencia { get; set; }
        public virtual DbSet<Matricula> Matricula { get; set; }
        public virtual DbSet<Oficina> Oficina { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<PessoaTipo> PessoaTipo { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
        public virtual DbSet<Turma> Turma { get; set; }
        public virtual DbSet<TurmaEstado> TurmaEstado { get; set; }
        public virtual DbSet<GradeProfessor> GradeProfessor { get; set; }
        public virtual DbSet<FrequenciaOFicina> FrequenciaOFicina { get; set; }
    }
}
