//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAprendiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int Id { get; set; }
        public int IdPessoa { get; set; }
        public int Endereco1 { get; set; }
        public Nullable<int> Complemento { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
