//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAprendiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frequencia
    {
        public int Id { get; set; }
        public int IdTurma { get; set; }
        public System.DateTime Data { get; set; }
        public bool IsFalta { get; set; }
        public Nullable<int> IdMatricula { get; set; }
    
        public virtual Matricula Matricula { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
