//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAprendiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeProfessor
    {
        public int IdTurma { get; set; }
        public int IdProfessor { get; set; }
        public int IdOficina { get; set; }
    
        public virtual Oficina Oficina { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
