//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAprendiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeMatricula
    {
        public int Id { get; set; }
        public int IdOficina { get; set; }
        public int IdMatricula { get; set; }
        public bool isCompleto { get; set; }
    
        public virtual Matricula Matricula { get; set; }
        public virtual Oficina Oficina { get; set; }
    }
}
