//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAprendiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int Id { get; set; }
        public int IdAprendiz { get; set; }
        public int IdCurso { get; set; }
        public System.DateTime DataMatricula { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
